name: Test workflow
on:
  workflow_dispatch:

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup uv
          uses: astral-sh/setup-uv@v3
          with:
            version: '0.5.4'
        
        - name: Run script
          env:
            ZOTERO_ID: 13765527
            ZOTERO_KEY: "rjC5fXUmbhqV2WniisbL2GDx"
            ARXIV_QUERY: "cat:cs.AI OR cat:cs.CV OR cat:cs.LG OR cat:cs.CL"
            SMTP_SERVER: "smtp.qq.com"
            SMTP_PORT: 456
            SENDER: "1719937539@qq.com"
            RECEIVER: "heu_handong@163.com"
            SENDER_PASSWORD: "hheviqbxmfudcbhe"
            MAX_PAPER_NUM: 50
          run: |
            uv run main.py --debug
